insert into public.simulations (
  id,
  channel,
  difficulty,
  category,
  language,
  title,
  sender,
  content,
  is_phishing,
  explanation,
  red_flags,
  source_model,
  created_by
)
values
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e01',
    'email',
    'easy',
    'delivery',
    'en',
    'Package delivery update',
    'FastTrack Delivery <support@track-fastparcel.com>',
    'Hello, your package delivery failed because the delivery address could not be verified. Please confirm your address within 12 hours at https://track-fastparcel.com/verify to avoid return fees.',
    true,
    'This is a phishing message because it creates urgency, uses an unfamiliar domain, and pushes the recipient to click a verification link before confirming whether a real shipment exists.',
    '["Creates urgency with a short deadline","Uses an unfamiliar sender domain","Requests action through a link instead of an official app or known order page"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e02',
    'email',
    'easy',
    'account_security',
    'en',
    'GitHub sign-in alert',
    'GitHub <noreply@github.com>',
    'We noticed a new sign-in to your GitHub account from Chrome on Windows. If this was you, no action is needed. Review account activity at https://github.com/settings/security-log.',
    false,
    'This is a legitimate security notice because it uses an official sender, does not demand a rushed response, and directs the user to the expected GitHub domain.',
    '["Official github.com sender","No request for password or secret code","Reasonable informational tone without threats"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e03',
    'sms',
    'medium',
    'bank',
    'en',
    null,
    'Bank Secure',
    'Suspicious transfer blocked. Verify your banking profile now: https://bank-secure-alert.co/login',
    true,
    'This SMS is phishing because it impersonates a bank, uses a suspicious domain, and pressures the recipient to react immediately through a login link.',
    '["Unknown or unofficial domain","Urgent banking scare tactic","Pushes login through SMS link"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e04',
    'whatsapp',
    'medium',
    'workplace',
    'en',
    null,
    'Maya | IT Helpdesk',
    'Hi, we are rotating VPN certificates today. Please upload your password manager recovery phrase here so we can verify your device.',
    true,
    'This message is phishing because legitimate IT teams do not ask for recovery phrases in chat, and the request is unrelated to normal certificate rotation procedures.',
    '["Requests highly sensitive data","Uses chat pressure instead of official workflow","Claim does not match standard IT process"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e05',
    'email',
    'easy',
    'shopping',
    'he',
    'עדכון על הזמנה',
    'StoreLine <orders@storeline.co.il>',
    'שלום, ההזמנה שלך יצאה למשלוח ותגיע מחר בין 10:00 ל-14:00. אפשר לעקוב אחרי המשלוח באזור האישי באתר הרשמי storeline.co.il.',
    false,
    'זו הודעה לגיטימית כי היא משתמשת בדומיין תואם למותג, לא מבקשת מידע רגיש, ולא מנסה להלחיץ את המשתמש לפעול מיד.',
    '["דומיין תואם למותג הרשמי","אין בקשה לסיסמה או לקוד","הטון אינפורמטיבי ולא מאיים"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e06',
    'sms',
    'medium',
    'delivery',
    'he',
    null,
    'חברת משלוחים',
    'החבילה שלך ממתינה במחסן. אשר/י עכשיו כתובת למשלוח מחדש: https://parcel-il-help.com',
    true,
    'זו הודעת פישינג כי היא מנצלת לחץ סביב משלוח, מציגה קישור שאינו שייך לחברת משלוחים מוכרת, ודוחפת לאישור מהיר דרך הודעת SMS.',
    '["קישור לא מזוהה","ניסוח לחוץ סביב משלוח","אין מספר הזמנה או פרטי מזהה אמינים"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e07',
    'whatsapp',
    'hard',
    'social',
    'he',
    null,
    'תמר',
    'היי, אני מחליפה טלפון ואיבדתי גישה לחשבון. תוכלי לשלוח לי את קוד האימות שקיבלת עכשיו? זה דחוף.',
    true,
    'זו הודעת הונאה חברתית כי היא מבקשת קוד אימות חד-פעמי, יוצרת תחושת דחיפות, ומנסה לנצל אמון אישי במקום תהליך מאובטח.',
    '["בקשה לקוד אימות אישי","תחושת דחיפות גבוהה","ניסיון לנצל קשר אישי במקום אימות מסודר"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e08',
    'email',
    'medium',
    'government',
    'en',
    'Digital tax certificate notice',
    'Public Services <alerts@citizen-tax-gov.net>',
    'Your digital tax certificate could not be issued. Review the attached notice today at https://citizen-tax-gov.net/review to avoid a filing delay.',
    true,
    'This is phishing because it imitates an official notice, creates deadline pressure, and uses an unofficial government-style domain.',
    '["Unofficial government-style domain","Deadline pressure around an official process","Pushes the user to review through a link"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e09',
    'sms',
    'easy',
    'government',
    'he',
    null,
    'Gov Update',
    'הבקשה לחידוש רישיון הנהיגה התקבלה. אפשר לעקוב אחר הסטטוס באזור האישי הממשלתי, ואין צורך בפעולה נוספת כרגע.',
    false,
    'זו הודעה לגיטימית כי היא אינפורמטיבית, לא לוחצת, ולא מבקשת פרטים רגישים או תשלום מיידי.',
    '["ניסוח אינפורמטיבי","אין דרישה דחופה","אין בקשה לפרטים סודיים"]'::jsonb,
    'seed',
    'seed'
  )
on conflict (id) do nothing;
