insert into public.simulations (
  id,
  channel,
  difficulty,
  category,
  language,
  title,
  sender,
  content,
  is_phishing,
  explanation,
  red_flags,
  source_model,
  created_by
)
values
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e01',
    'email',
    'easy',
    'delivery',
    'en',
    'Package delivery update',
    'FastTrack Delivery <support@track-fastparcel.com>',
    'Hello, your package delivery failed because the delivery address could not be verified. Please confirm your address within 12 hours at https://track-fastparcel.com/verify to avoid return fees.',
    true,
    'This is a phishing message because it creates urgency, uses an unfamiliar domain, and pushes the recipient to click a verification link before confirming whether a real shipment exists.',
    '["Creates urgency with a short deadline","Uses an unfamiliar sender domain","Requests action through a link instead of an official app or known order page"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e02',
    'email',
    'easy',
    'account_security',
    'en',
    'GitHub sign-in alert',
    'GitHub <noreply@github.com>',
    'We noticed a new sign-in to your GitHub account from Chrome on Windows. If this was you, no action is needed. Review account activity at https://github.com/settings/security-log.',
    false,
    'This is a legitimate security notice because it uses an official sender, does not demand a rushed response, and directs the user to the expected GitHub domain.',
    '["Official github.com sender","No request for password or secret code","Reasonable informational tone without threats"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e03',
    'sms',
    'medium',
    'bank',
    'en',
    null,
    'Bank Secure',
    'Suspicious transfer blocked. Verify your banking profile now: https://bank-secure-alert.co/login',
    true,
    'This SMS is phishing because it impersonates a bank, uses a suspicious domain, and pressures the recipient to react immediately through a login link.',
    '["Unknown or unofficial domain","Urgent banking scare tactic","Pushes login through SMS link"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e04',
    'whatsapp',
    'medium',
    'workplace',
    'en',
    null,
    'Maya | IT Helpdesk',
    'Hi, we are rotating VPN certificates today. Please upload your password manager recovery phrase here so we can verify your device.',
    true,
    'This message is phishing because legitimate IT teams do not ask for recovery phrases in chat, and the request is unrelated to normal certificate rotation procedures.',
    '["Requests highly sensitive data","Uses chat pressure instead of official workflow","Claim does not match standard IT process"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e05',
    'email',
    'easy',
    'shopping',
    'he',
    'עדכון על הזמנה',
    'StoreLine <orders@storeline.co.il>',
    'שלום, ההזמנה שלך יצאה למשלוח ותגיע מחר בין 10:00 ל-14:00. אפשר לעקוב אחרי המשלוח באזור האישי באתר הרשמי storeline.co.il.',
    false,
    'זו הודעה לגיטימית כי היא משתמשת בדומיין תואם למותג, לא מבקשת מידע רגיש, ולא מנסה להלחיץ את המשתמש לפעול מיד.',
    '["דומיין תואם למותג הרשמי","אין בקשה לסיסמה או לקוד","הטון אינפורמטיבי ולא מאיים"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e06',
    'sms',
    'medium',
    'delivery',
    'he',
    null,
    'חברת משלוחים',
    'החבילה שלך ממתינה במחסן. אשר/י עכשיו כתובת למשלוח מחדש: https://parcel-il-help.com',
    true,
    'זו הודעת פישינג כי היא מנצלת לחץ סביב משלוח, מציגה קישור שאינו שייך לחברת משלוחים מוכרת, ודוחפת לאישור מהיר דרך הודעת SMS.',
    '["קישור לא מזוהה","ניסוח לחוץ סביב משלוח","אין מספר הזמנה או פרטי מזהה אמינים"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e07',
    'whatsapp',
    'hard',
    'social',
    'he',
    null,
    'תמר',
    'היי, אני מחליפה טלפון ואיבדתי גישה לחשבון. תוכלי לשלוח לי את קוד האימות שקיבלת עכשיו? זה דחוף.',
    true,
    'זו הודעת הונאה חברתית כי היא מבקשת קוד אימות חד-פעמי, יוצרת תחושת דחיפות, ומנסה לנצל אמון אישי במקום תהליך מאובטח.',
    '["בקשה לקוד אימות אישי","תחושת דחיפות גבוהה","ניסיון לנצל קשר אישי במקום אימות מסודר"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e08',
    'email',
    'medium',
    'government',
    'en',
    'Digital tax certificate notice',
    'Public Services <alerts@citizen-tax-gov.net>',
    'Your digital tax certificate could not be issued. Review the attached notice today at https://citizen-tax-gov.net/review to avoid a filing delay.',
    true,
    'This is phishing because it imitates an official notice, creates deadline pressure, and uses an unofficial government-style domain.',
    '["Unofficial government-style domain","Deadline pressure around an official process","Pushes the user to review through a link"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e09',
    'sms',
    'easy',
    'government',
    'he',
    null,
    'Gov Update',
    'הבקשה לחידוש רישיון הנהיגה התקבלה. אפשר לעקוב אחר הסטטוס באזור האישי הממשלתי, ואין צורך בפעולה נוספת כרגע.',
    false,
    'זו הודעה לגיטימית כי היא אינפורמטיבית, לא לוחצת, ולא מבקשת פרטים רגישים או תשלום מיידי.',
    '["ניסוח אינפורמטיבי","אין דרישה דחופה","אין בקשה לפרטים סודיים"]'::jsonb,
    'seed',
    'seed'
  )
  ,
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e0a',
    'email',
    'medium',
    'bank',
    'en',
    'Updated supplier bank details',
    'Sharon Medical Supplies <billing@sharon-medical-ap.co>',
    'Please note that our banking details changed for invoice 49281. Settle the payment today to avoid delaying the weekly delivery to the home. Updated transfer details are attached.',
    true,
    'This message is suspicious because it combines invoice pressure, a banking change, and a sender domain that does not match the supplier name.',
    '["Requests payment to new bank details","Creates urgency around an operational delivery","Sender domain does not match the supplier brand"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e0b',
    'whatsapp',
    'medium',
    'social',
    'he',
    null,
    'רבקה | מנהלת משמרת',
    'בוקר טוב, אני כרגע עם המשפחה של אחד הדיירים. תשלחי לי כאן את קוד האימות שהגיע כדי שאוכל לסגור את בקשת התשלום הדחופה.',
    true,
    'זו הודעת התחזות משום שהיא מבקשת קוד אימות ב-WhatsApp, יוצרת לחץ, ומשתמשת בזהות מוכרת כדי לעקוף תהליך עבודה רגיל.',
    '["בקשה לקוד אימות אישי","לחץ סביב תשלום דחוף","שימוש בזהות מוכרת ב-WhatsApp"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e0c',
    'sms',
    'easy',
    'delivery',
    'he',
    null,
    'בית מרקחת תורן',
    'משלוח התרופות לדיירת רות כהן יגיע בין 14:00 ל-16:00. אין צורך בפעולה נוספת. לעדכון פרטי שליח יש לפנות לספק המוכר שלכם בלבד.',
    false,
    'זו הודעה לגיטימית כי היא אינפורמטיבית, לא מבקשת קישור או קוד, ולא מפעילה לחץ חריג.',
    '["טון אינפורמטיבי","אין קישור חשוד","אין בקשה לפרטי גישה או תשלום"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e0d',
    'email',
    'easy',
    'workplace',
    'en',
    'Weekly care coordination schedule',
    'Operations Desk <ops@beitshalom-care.org>',
    'Attached is the updated coordination schedule for meals, transport, and visiting hours for next week. No login or payment action is required.',
    false,
    'This looks legitimate because it is a routine internal update, it does not ask for secrets, and it matches normal operational coordination.',
    '["Routine operational content","No login or payment request","Matches normal staff workflow"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e0e',
    'email',
    'medium',
    'social',
    'en',
    'Parent message about urgent form',
    'Yael Cohen <yael.parent.forms@outlook-reset.net>',
    'Hello teacher, the principal said every parent must open this attendance form before noon or the child will be marked absent for tomorrow. Please review and confirm here: https://school-parent-form.net/open',
    true,
    'This is phishing because it impersonates a parent workflow, creates time pressure, and pushes the teacher to an unfamiliar external link.',
    '["Unfamiliar form domain","Urgency around attendance","Uses a parent identity to pressure action"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e0f',
    'email',
    'medium',
    'account_security',
    'he',
    'אזהרת איפוס סיסמה למשתמש בית ספרי',
    'Microsoft School Access <security@ms-school-verify.co>',
    'זוהה ניסיון חריג להתחבר לחשבון בית הספר שלך. יש לאפס סיסמה בתוך 30 דקות כדי למנוע חסימת גישה: https://ms-school-verify.co/reset',
    true,
    'זו הודעת פישינג כי היא משתמשת בלחץ זמן, בדומיין שאינו שייך ל-Microsoft, ומפנה לאיפוס סיסמה דרך קישור חיצוני.',
    '["דומיין לא רשמי","לחץ זמן חריג","איפוס סיסמה דרך קישור חיצוני"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e10',
    'email',
    'easy',
    'government',
    'he',
    'עדכון לוח חופשות ממשרד החינוך',
    'משרד החינוך <notifications@edu.gov.il>',
    'פורסם עדכון ללוח החופשות ולימי ההיערכות לשנה הקרובה. ניתן לצפות במסמך דרך פורטל העובדים הרשמי. אין צורך למסור סיסמה או לבצע פעולה מיידית.',
    false,
    'זו הודעה לגיטימית כי היא אינפורמטיבית, משתמשת בדומיין ממשלתי צפוי, ואינה מבקשת קוד, סיסמה או תשלום.',
    '["דומיין ממשלתי צפוי","טון רגוע","אין דרישה לפרטים רגישים"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e11',
    'whatsapp',
    'hard',
    'workplace',
    'en',
    null,
    'Principal Office',
    'Please send the latest staff directory and your Google verification code here now. We need to reopen two accounts before the ministry meeting starts.',
    true,
    'This chat is suspicious because it asks for sensitive internal data and a verification code through WhatsApp under artificial urgency.',
    '["Requests a verification code in chat","Asks for internal staff data","Uses urgent authority pressure"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e12',
    'email',
    'medium',
    'bank',
    'en',
    'Donation settlement update',
    'Annual Giving Desk <donations@giving-flow-help.org>',
    'Our campaign processor changed the settlement account for this week only. Please transfer the donor payout balance to the updated bank details before 16:00 so receipts can be issued on time.',
    true,
    'This is phishing because it mixes donation operations with a last-minute bank change and unusual payment urgency.',
    '["New bank details for donations","Urgent transfer request","Tries to bypass normal finance workflow"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e13',
    'whatsapp',
    'medium',
    'social',
    'he',
    null,
    'ליטל | רכזת מתנדבים',
    'היי, אני צריכה בדחיפות את קובץ כל המתנדבים של מחר, כולל מספרי טלפון, וגם את קוד הכניסה שקיבלת עכשיו כדי לפתוח את הקבוצה החדשה.',
    true,
    'זו הודעת התחזות כי היא מבקשת גם מידע אישי על מתנדבים וגם קוד גישה דרך שיחת WhatsApp דחופה.',
    '["בקשה לפרטי מתנדבים","בקשה לקוד גישה","לחץ לבצע פעולה מחוץ לתהליך הרגיל"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e14',
    'email',
    'easy',
    'government',
    'en',
    'Association filing reminder',
    'Registrar Notifications <no-reply@amutot.gov.il>',
    'This is a reminder that the annual association filing window opens next week. Please review the requirements in the official portal. No immediate action is needed today.',
    false,
    'This looks legitimate because it uses an expected government sender, keeps the tone informational, and does not ask for payment or credentials by email.',
    '["Expected official sender","Informational reminder","No urgent login or payment request"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e15',
    'email',
    'medium',
    'shopping',
    'he',
    'בקשת תשלום לספק אירוע',
    'ספק אירוע קהילתי <events-vendor@quick-transfer-pay.co>',
    'כדי לשריין את ההגברה לאירוע העמותה מחר, יש להעביר מקדמה עוד היום לחשבון המעודכן המצורף. אם לא תשלמו עכשיו נאבד את הסלוט.',
    true,
    'זו הודעת פישינג כי היא דוחפת להעברת מקדמה מיידית, משתמשת בחשבון מעודכן לא מוכר, ומנסה לעקוף בדיקת ספק רגילה.',
    '["לחץ לשלם מיד","פרטי תשלום מעודכנים ולא מוכרים","איום באובדן ספק אם לא תפעלו עכשיו"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e16',
    'email',
    'medium',
    'government',
    'he',
    'עדכון ארנונה וגבייה',
    'מרכז שירות עירוני <billing@arnona-city-update.net>',
    'נמצאה חריגה בפרטי הגבייה של הרשות המקומית. יש לעיין במסמך המצורף ולהתחבר עוד היום כדי למנוע עיכוב בהעברת התקבולים.',
    true,
    'זו הודעת פישינג כי היא מתחזה להודעה רשמית, לוחצת לפעולה מהירה, ומשתמשת בדומיין שנראה ממשלתי אך אינו רשמי.',
    '["דומיין רשמי למראה אך לא אמין","לחץ סביב גבייה עירונית","בקשה להתחברות דרך קישור"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e17',
    'email',
    'medium',
    'bank',
    'en',
    'Vendor payment rerouting request',
    'Gal Procurement Services <accounts@gal-procurement-payments.com>',
    'Please update the bank destination for the street-lighting invoice batch before approvals close today. The old account is no longer active and payment must be reissued manually.',
    true,
    'This message is suspicious because it asks for a bank-detail change on a procurement payment and uses urgency to bypass verification.',
    '["Bank account change request","Procurement payment pressure","Unverified vendor billing domain"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e18',
    'sms',
    'easy',
    'workplace',
    'he',
    null,
    'מוקד תפעול עירוני',
    'מערכת פניות התושבים תעבור תחזוקה בין 18:00 ל-19:00. אין צורך בפעולה נוספת. כל שינוי יופיע בפורטל העירוני הרגיל.',
    false,
    'זו הודעה לגיטימית כי היא מודיעה על תחזוקה שגרתית, לא מבקשת קוד או תשלום, ומפנה לערוץ עבודה מוכר.',
    '["הודעת תחזוקה שגרתית","אין דרישה לפעולה דחופה","הפניה לפורטל קיים ומוכר"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e19',
    'whatsapp',
    'hard',
    'workplace',
    'en',
    null,
    'Municipal Director',
    'I am stepping into a meeting now. Approve the attached purchase summary and send me the code you just received so finance can release the vendor payment before noon.',
    true,
    'This message combines authority impersonation, payment pressure, and a request for a verification code in chat.',
    '["Authority impersonation in WhatsApp","Requests a verification code","Urgent vendor payment approval"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e1a',
    'email',
    'medium',
    'bank',
    'he',
    'חשבונית דחופה עם עדכון חשבון בנק',
    'ספק משרד וציוד <billing@office-pay-support.co>',
    'מצורפת חשבונית עבור הזמנת ציוד למשרד. שימו לב: פרטי הבנק עודכנו ויש לשלם עוד היום כדי למנוע עיכוב באספקה.',
    true,
    'זו הודעת פישינג כי היא משלבת חשבונית, שינוי פרטי בנק ולחץ זמן שמיועד לעקוף בדיקה מול הספק.',
    '["שינוי פרטי בנק","לחץ לשלם היום","דומיין חיוב שאינו תואם לספק"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e1b',
    'sms',
    'medium',
    'delivery',
    'en',
    null,
    'Courier IL',
    'Your business parcel is waiting for customs release. Pay the handling fee in the next hour: https://courier-il-fee.net/pay',
    true,
    'This is phishing because it pressures the user to pay a small courier fee through an unfamiliar SMS link.',
    '["Courier fee demand by SMS","Short deadline","Unofficial payment domain"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e1c',
    'email',
    'easy',
    'account_security',
    'en',
    'Microsoft sign-in notification',
    'Microsoft account team <account-security-noreply@accountprotection.microsoft.com>',
    'We noticed a successful sign-in to your Microsoft 365 account from Tel Aviv using Chrome on Windows. If this was you, no further action is required.',
    false,
    'This looks legitimate because it uses an expected Microsoft sender, gives context, and does not ask the user to reset credentials from the email.',
    '["Expected Microsoft sender","Informational security notice","No urgent credential request"]'::jsonb,
    'seed',
    'seed'
  ),
  (
    '86c1d8e4-0d2c-412f-9c41-b63c3a816e1d',
    'whatsapp',
    'medium',
    'shopping',
    'he',
    null,
    'אורי | ספק',
    'היי, עברתי למספר חדש. תשלחי לי כאן את ההזמנה האחרונה ואת פרטי הנהלת החשבונות כדי שאעדכן את החשבונית לפני השליח.',
    true,
    'זו הודעת התחזות כי היא משתמשת במספר חדש, מבקשת מידע עסקי וחשבונאי, ומנסה לעקוף אימות ספק רגיל דרך WhatsApp.',
    '["מספר חדש ולא מאומת","בקשה לפרטי רכש וחשבונאות","ניסיון לעקוף אימות ספק רגיל"]'::jsonb,
    'seed',
    'seed'
  )
on conflict (id) do nothing;
