export const ownerConsoleCopy = {
  he: {
    eyebrow: 'קונסולת בעלים',
    title: 'ניהול ארגונים פשוט וברור',
    subtitle: 'מרכז אחד לניהול מסלולים, חסימות ומעקב. בכל רגע רואים רק את מה שצריך כדי לפעול.',
    primaryAction: 'מעבר לארגונים לטיפול',
    refresh: 'רענון נתונים',
    badges: {
      total: 'ארגונים',
      attention: 'דורשים טיפול',
      blocked: 'חסומים',
      active: 'פעילים השבוע',
    },
    sections: {
      overview: 'תמונת מצב',
      organizations: 'ארגונים',
      plans: 'מסלולים והרשאות',
      activity: 'פעילות ומעקב',
    },
    filters: {
      label: 'תצוגה',
      searchPlaceholder: 'חיפוש לפי שם, slug או סגמנט',
      all: 'כל הארגונים',
      attention: 'דורשים טיפול',
      free: 'חינמי',
      trial: 'ניסיון',
      paid: 'בתשלום',
      blocked: 'חסומים',
    },
    statuses: {
      free: 'חינמי',
      trial: 'ניסיון',
      active_paid: 'בתשלום',
      past_due: 'באיחור',
      blocked: 'חסום',
    },
    planTypes: {
      free: 'חינם',
      growth: 'Growth',
      scale: 'Scale',
    },
    segments: {
      nursing_home: 'בית אבות',
      education: 'חינוך',
      nonprofit: 'עמותה',
      municipality: 'רשות מקומית',
      smb: 'עסק קטן',
      other: 'אחר',
    },
    followUp: {
      label: 'סטטוס פנייה',
      noteTitle: 'הערת מעקב',
      noteDescription: 'הערה קצרה לצוות המכירות או המעקב.',
      notePlaceholder: 'מה כדאי לזכור לפני השיחה הבאה?',
      billingTitle: 'הערת מסלול / חיוב',
      billingDescription: 'מידע פנימי על מסלול, מחיר או חסימה.',
      billingPlaceholder: 'למשל: ביקשו הצעת מחיר מוזלת עד סוף החודש.',
      options: {
        new: 'חדש',
        contacted: 'בוצעה פנייה',
        offered_discount: 'הוצעה הנחה',
        upgraded: 'שודרג',
      },
      saveNote: 'שמירת הערה',
      saveBilling: 'שמירת הערת מסלול',
    },
    overview: {
      title: 'מה חשוב לראות קודם',
      description: 'סיכום קצר של המצב הנוכחי, בלי עומס.',
      attentionTitle: 'מה דורש טיפול עכשיו',
      attentionDescription: 'רשימת הארגונים שכדאי לפתוח קודם.',
      attentionEmpty: 'כרגע אין ארגונים עם אותות שמצריכים טיפול מיידי.',
      recentTitle: 'ארגונים חדשים',
      recentDescription: 'הארגונים האחרונים שנוספו למערכת.',
      recentEmpty: 'עדיין לא נוספו ארגונים חדשים.',
      mixTitle: 'פיזור מסלולים',
      mixDescription: 'כך נראית חלוקת המסלולים כרגע.',
      openPlans: 'פתיחת ניהול מסלול',
    },
    organizations: {
      title: 'רשימת ארגונים',
      description: 'חיפוש מהיר ובחירת ארגון לעבודה.',
      empty: 'לא נמצאו ארגונים לתצוגה הזו.',
      selectedTitle: 'הארגון הנבחר',
      selectedDescription: 'כאן רואים את התמונה המהירה לפני מעבר לפעולות.',
      openPlans: 'ניהול מסלול והרשאות',
      openActivity: 'צפייה בפעילות',
      noSelection: 'בחרו ארגון מהרשימה כדי לראות פרטים.',
      members: 'משתמשים פעילים',
      totalMembers: 'סה״כ משתמשים',
      lastActivity: 'פעילות אחרונה',
      pendingInvites: 'הזמנות ממתינות',
      segment: 'סגמנט',
      slug: 'Slug',
    },
    plans: {
      title: 'מסלול, גישה ומעקב',
      description: 'כל שינוי כאן חל מיד על מגבלות המשתמשים והגישה.',
      orgLabel: 'ארגון',
      noSelection: 'בחרו ארגון כדי לנהל מסלול, חסימה ומעקב.',
      accessTitle: 'מצב נוכחי',
      accessDescription: 'תמונה קצרה של המסלול והמגבלות.',
      actionsTitle: 'פעולות מהירות',
      actionsDescription: 'הפעולות הנפוצות ביותר לניהול הארגון.',
      limitLabel: 'מקסימום משתמשים',
      limitHint: 'מעדכנים ושומרים רק כשצריך.',
      saveLimit: 'שמירת מגבלה',
      trialEnds: 'סיום ניסיון',
      memberUsage: 'שימוש במכסה',
      currentPlan: 'מסלול',
      currentStatus: 'סטטוס',
      followUpLabel: 'סטטוס מעקב',
      startTrial: 'התחלת ניסיון',
      markPaid: 'סימון בתשלום',
      setFree: 'החזרה לחינם',
      block: 'חסימה',
      unblock: 'ביטול חסימה',
    },
    activity: {
      title: 'פעילות ומעקב',
      description: 'מי פעיל, מי נתקע, ומי בשל לשיחה מסחרית.',
      opportunitiesTitle: 'ארגונים שכדאי לפנות אליהם',
      opportunitiesDescription: 'שימוש פעיל, מגבלה או חסימה שמצריכים מעקב.',
      opportunitiesEmpty: 'כרגע אין ארגונים עם אותות מסחריים בולטים.',
      activeTitle: 'פעילות אחרונה',
      activeDescription: 'מי השתמש לאחרונה במערכת.',
      activeEmpty: 'עדיין אין פעילות עדכנית להצגה.',
      quietTitle: 'שקטים כרגע',
      quietDescription: 'ארגונים בלי פעילות חדשה ב-30 הימים האחרונים.',
      quietEmpty: 'אין ארגונים שקטים כרגע.',
      pendingInvites: 'הזמנות פתוחות',
      attempts7: 'נסיונות 7 ימים',
      attempts30: 'נסיונות 30 ימים',
      openPlans: 'לניהול המסלול',
    },
    alerts: {
      blocked: 'גישה חסומה',
      atLimit: 'הגיע למגבלה',
      likely: 'כדאי לפנות',
      inactive: 'ללא פעילות עדכנית',
    },
    messages: {
      loadError: 'לא הצלחנו לטעון את קונסולת הבעלים.',
      updateError: 'לא הצלחנו לעדכן את הארגון.',
      updated: 'הארגון עודכן.',
      invalidLimit: 'יש להזין מגבלה תקינה של משתמש אחד לפחות.',
    },
    common: {
      noDate: 'אין נתון עדיין',
    },
  },
  en: {
    eyebrow: 'Owner console',
    title: 'Simple, focused organization management',
    subtitle: 'One place for plans, access, and follow-up. Each section shows only what matters right now.',
    primaryAction: 'Review follow-up orgs',
    refresh: 'Refresh data',
    badges: {
      total: 'Organizations',
      attention: 'Need follow-up',
      blocked: 'Blocked',
      active: 'Active this week',
    },
    sections: {
      overview: 'Overview',
      organizations: 'Organizations',
      plans: 'Plans & Access',
      activity: 'Activity',
    },
    filters: {
      label: 'View',
      searchPlaceholder: 'Search by name, slug, or segment',
      all: 'All organizations',
      attention: 'Need follow-up',
      free: 'Free',
      trial: 'Trial',
      paid: 'Paid',
      blocked: 'Blocked',
    },
    statuses: {
      free: 'Free',
      trial: 'Trial',
      active_paid: 'Paid',
      past_due: 'Past due',
      blocked: 'Blocked',
    },
    planTypes: {
      free: 'Free',
      growth: 'Growth',
      scale: 'Scale',
    },
    segments: {
      nursing_home: 'Nursing home',
      education: 'Education',
      nonprofit: 'Nonprofit',
      municipality: 'Municipality',
      smb: 'SMB',
      other: 'Other',
    },
    followUp: {
      label: 'Follow-up status',
      noteTitle: 'Internal follow-up note',
      noteDescription: 'A short note for sales or support follow-up.',
      notePlaceholder: 'What should the next conversation include?',
      billingTitle: 'Plan / billing note',
      billingDescription: 'Internal context about plan, pricing, or access.',
      billingPlaceholder: 'For example: asked for a discounted quote before month end.',
      options: {
        new: 'New',
        contacted: 'Contacted',
        offered_discount: 'Offered discount',
        upgraded: 'Upgraded',
      },
      saveNote: 'Save note',
      saveBilling: 'Save billing note',
    },
    overview: {
      title: 'What matters first',
      description: 'A short snapshot without dashboard overload.',
      attentionTitle: 'Needs attention now',
      attentionDescription: 'Open these organizations first.',
      attentionEmpty: 'No organizations currently require immediate follow-up.',
      recentTitle: 'Recent organizations',
      recentDescription: 'Latest organizations added to the platform.',
      recentEmpty: 'No recent organizations yet.',
      mixTitle: 'Plan mix',
      mixDescription: 'Current distribution across plans.',
      openPlans: 'Open plan controls',
    },
    organizations: {
      title: 'Organization list',
      description: 'Search quickly and pick one org to work on.',
      empty: 'No organizations match this view.',
      selectedTitle: 'Selected organization',
      selectedDescription: 'Quick context before moving into actions.',
      openPlans: 'Manage plan & access',
      openActivity: 'View activity',
      noSelection: 'Choose an organization from the list to see details.',
      members: 'Active members',
      totalMembers: 'Total members',
      lastActivity: 'Last activity',
      pendingInvites: 'Pending invites',
      segment: 'Segment',
      slug: 'Slug',
    },
    plans: {
      title: 'Plan, access, and follow-up',
      description: 'Changes here apply immediately to access and member limits.',
      orgLabel: 'Organization',
      noSelection: 'Choose an organization to manage plan, blocking, and follow-up.',
      accessTitle: 'Current state',
      accessDescription: 'A short summary of plan and limits.',
      actionsTitle: 'Quick actions',
      actionsDescription: 'The most common management actions for this organization.',
      limitLabel: 'Max members',
      limitHint: 'Update only when you need to change access.',
      saveLimit: 'Save member limit',
      trialEnds: 'Trial ends',
      memberUsage: 'Member usage',
      currentPlan: 'Plan',
      currentStatus: 'Status',
      followUpLabel: 'Follow-up status',
      startTrial: 'Start trial',
      markPaid: 'Mark paid',
      setFree: 'Set free',
      block: 'Block',
      unblock: 'Unblock',
    },
    activity: {
      title: 'Activity and follow-up',
      description: 'See who is active, who is stalled, and who is ready for outreach.',
      opportunitiesTitle: 'Best outreach opportunities',
      opportunitiesDescription: 'Usage, limits, and blocked access worth following up on.',
      opportunitiesEmpty: 'No strong commercial signals right now.',
      activeTitle: 'Latest activity',
      activeDescription: 'Organizations with the most recent usage.',
      activeEmpty: 'No recent activity to show yet.',
      quietTitle: 'Quiet right now',
      quietDescription: 'Organizations with no new activity in the last 30 days.',
      quietEmpty: 'No quiet organizations right now.',
      pendingInvites: 'Open invites',
      attempts7: 'Attempts in 7d',
      attempts30: 'Attempts in 30d',
      openPlans: 'Open plan controls',
    },
    alerts: {
      blocked: 'Access blocked',
      atLimit: 'At member limit',
      likely: 'Worth contacting',
      inactive: 'No recent activity',
    },
    messages: {
      loadError: 'Unable to load the owner console.',
      updateError: 'Unable to update the organization.',
      updated: 'Organization updated.',
      invalidLimit: 'Enter a valid member limit of at least 1.',
    },
    common: {
      noDate: 'No data yet',
    },
  },
} as const
